"""Shared paths for files generated by the example scripts."""

from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT_DIR = PROJECT_ROOT / "example-artifacts"
_OUTPUT_ENV = "PYKOKORO_EXAMPLE_OUTPUT_DIR"


def artifact_dir() -> Path:
    """Return and create the directory used for generated example artifacts."""
    path = Path(os.environ.get(_OUTPUT_ENV, ARTIFACT_DIR))
    path.mkdir(parents=True, exist_ok=True)
    return path.resolve()


def artifact_path(name: str | Path) -> Path:
    """Return a generated-artifact path below the configured artifact directory."""
    root = artifact_dir()
    path = (root / name).resolve()
    if path != root and root not in path.parents:
        raise ValueError(f"artifact path escapes {root}: {name}")
    path.parent.mkdir(parents=True, exist_ok=True)
    return path
